GREEN="\033[33m"
YELLOW="\033[33m"
RED="\033[33m"
WHITE="\033[33m"
MAGENTA="\033[95m"
ARC_RED="\033[41m"
ARC_ORANGE="\033[101m"
ARC_YELLOW="\033[43m"
ARC_GREEN="\033[102m"
ARC_BLUE="\033[44m"
ARC_MAGENTA="\033[45m"
ARC_NC="\033[49m"

nyan() {
	clear
	echo -e "${MAGENTA}                             "
	echo -e "          ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄         "
	echo -e "        ▄▀░░░░░░░░░░░░▄░░░░░░░▀▄       "
	echo -e "        █░░▄░░░░▄░░░░░░░░░░░░░░█       "
	echo -e "${ARC_RED}        ${ARC_NC}█░░░░░░░░░░░░▄█▄▄░░▄░░░█ ▄▄▄   "
	echo -e "${ARC_ORANGE} ▄▄▄▄▄  ${ARC_NC}█░░░░░░▀░░░░▀█░░▀▄░░░░░█▀▀░██  "
	echo -e "${ARC_YELLOW} ${ARC_NC}██▄▀██${ARC_YELLOW}▄${ARC_NC}█░░░▄░░░░░░░██░░░░▀▀▀▀▀░░░░██  "
	echo -e "${ARC_GREEN}  ▀${ARC_NC}██▄▀██░░░░░░░░▀░██▀░░░░░░░░░░░░░▀██ "
	echo -e "${ARC_BLUE}    ▀${ARC_NC}████░▀░░░░▄░░░██░░░${GREEN}▄█${MAGENTA}░░░░▄░${GREEN}▄█${MAGENTA}░░██ "
	echo -e "${ARGC_MAGENTA}       ▀${ARC_NC}█░░░░▄░░░░░██░░░░▄░░░▄░░▄░░░██ "
	echo -e "       ▄█▄░░░░░░░░░░░▀▄░░▀▀▀▀▀▀▀▀░░▄▀  "
	echo -e "      █▀▀█████████▀▀▀▀████████████▀    "
	echo -e "      ████▀   ███▀      ▀███  ▀██▀     "
	echo -e "\n       ♥♥♥  ft_printf tester  ♥♥♥\n"
}
